version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'
        volumes:
            - ./server:/var/www/html

    #composer:
        #image: composer
        #volumes:
        #  - ./server:/var/www/html
        #working_dir: /var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        volumes:
           # Pour lancer un dump automatiquement au montage du conteneur
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1

    ##install composer and firebase-jwt and add it to php
    composer:
        image: composer
        restart: 'no'
        volumes:
            - ./server:/var/www/html
        working_dir: /var/www/html
        environment:
            - COMPOSER_HOME=/var/www/html/.composer
            - COMPOSER_CACHE_DIR=/var/www/html/.composer/cache
        command: composer install
        depends_on:
            - php